### PR TITLE
time: make time.Weekday data type public so that it can be pattern matched

### PR DESCRIPTION
**Pull request by bikallem**
This PR makes `time.Weekday` exportable/public so that consumers of this package can pattern match on it. My use case is that I have to get the weekday of the the parsed PlainDateTime and do certain action based on the returned value. 

At the moment I have to pattern match on a string value, like so
```
  let d = @time.PlainDateTime::of!(
    2000,
    2,
    29,
    hour=1,
    minute=10,
    second=30,
    nanosecond=1000,
  )

match d.weekday().to_string() {
"Monday" => ..
"Tuesday" => ...
"WednesDay" => ...
"Thursday" => ...
"Friday" => ...
"Saturday" => ...
"Sunday" => ...
_ => raise .. //
```
The `d.weekday()` value is already parsed and deemed to be valid, i.e. `PlainDateTime.of` is a success. It seems rather inconvenient to have to handle/pattern-match a case that we know will never occur. Exposing `@time.Weekday` as `pub` and exporting in `time.mbti` will remove this redundant match case. Also in a few instances I have found pattern matching on strings is rather fragile since there are chances of typos in the string which the compiler can't highlight during build time. Finally, `Weekday` values are rather stable (.i.e. they are not going to be changed, I think), so I think making it public should be quite future proof.

### CODE REVIEW

**Comment by peter-jerry-ye** [comment]
@yj-qin What do you think?

**Comment by yj-qin** [comment]
LGTM. It makes sense.

**Comment by peter-jerry-ye** [comment]
@bikallem Can you please rerun `moon info` and regenerate the `mbti` file?

**Comment by bikallem** [comment]
@peter-jerry-ye Done.

**Comment by bikallem** [comment]
Looks like CI failing due to CLA. Where/how can I sign it?

**Comment by Young-Flash** [comment]
> Looks like CI failing due to CLA. Where/how can I sign it?

https://www.moonbitlang.com/cla

**Comment by Yoorkin** [comment]
> > Looks like CI failing due to CLA. Where/how can I sign it?
> 
> https://www.moonbitlang.com/cla

We don't require the contributor to sign a CLA anymore, so I just removed the CI check.

**Pull request merged**
